name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    outputs:
      srversion: ${{ steps.setoutput.outputs.srversion }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false # Make sure the release step uses its own credentials.
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@zbmed'
      - name: Run npm clean install
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TREEVIEW_SECRET }}
      - name: Run npm build
        run: npm run build --if-present
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TREEVIEW_SECRET }}
      - name: Run semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TO_PUSH }}
          NODE_AUTH_TOKEN: ${{ secrets.PAT_TO_PUSH }}
          SCOPE: '@nfdi4health'
      - name: Capture version number
        run: echo "SRVERSION=$(npx semantic-release --dry-run | grep -oP 'Found git tag v\K\d+\.\d+\.\d+')" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TO_PUSH }}
          NODE_AUTH_TOKEN: ${{ secrets.PAT_TO_PUSH }}
          SCOPE: '@nfdi4health'
      - name: Set output
        id: setoutput
        run: echo "srversion=$SRVERSION" >> "$GITHUB_OUTPUT"
      - name: Debug SRVERSION
        run: echo "SRVERSION is $SRVERSION"
      - name: Run npm build:plainJS
        run: npm run build:plainJS
      - name: Set Git Author Identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Configure Git to Use PAT for Authentication
        run: |
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n '${{ secrets.GH_PAT }}' | base64)"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ env.SRVERSION }}
      - name: Copy as Latest to js-modules branch
        if: env.SRVERSION != ''
        run: |
          npx gh-pages-multi deploy -s dist_plainjs -b js-modules --no-history -t latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy Version to js-modules branch
        if: env.SRVERSION != ''
        env:
          SRVERSION: ${{ needs.build.outputs.srversion }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx gh-pages-multi deploy -s dist_plainjs -b js-modules --no-history -t "$SRVERSION"
  documentation:
    if: github.ref == 'refs/heads/feat/plainJS-sb-integration'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@zbmed'
          token: ${{ secrets.TREEVIEW_SECRET }}
      - name: Install and Build HTML Storybook
        run: |
          npm install
          npm run build-storybook-html -- -o html
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TREEVIEW_SECRET }}
      - name: Upload html artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'html'
      - name: Install and Build React Storybook
        run: |
          npm install
          npm run build-storybook-react -- -o react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TREEVIEW_SECRET }}
      - name: Upload react artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'react'
      - name: Install and Build Composed Storybook
        run: |
          npm install
          npm run build-storybook -- -o public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TREEVIEW_SECRET }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'public'
      - name: Set Git Author Identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Configure Git to Use PAT for Authentication
        run: |
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n '${{ secrets.GH_PAT }}' | base64)"
      - name: Deploy as Latest to GitHub Pages
        run: |
          npx gh-pages-multi deploy -s react --no-history -t react/latest
          npx gh-pages-multi deploy -s html --no-history -t html/latest
          npx gh-pages-multi deploy -s public --no-history
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Use SRVERSION
        env:
          SRVERSION: ${{ needs.build.outputs.srversion }}
        run: echo "SRVERSION is $SRVERSION"
      - name: Deploy Version to GitHub Pages
        if: env.SRVERSION != ''
        env:
          SRVERSION: ${{ needs.build.outputs.srversion }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx gh-pages-multi deploy -s react --no-history -t react/"$SRVERSION"
          npx gh-pages-multi deploy -s html --no-history -t html/"$SRVERSION"
          npx gh-pages-multi deploy -s public --no-history -t "$SRVERSION"