# This workflow will build the storybook documentation with GitHub Pages

name: Build Storybook and publish to GH Pages

on:
  push:
    branches:
      - main

env:
  widgetsDocVersion_PATH: /

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update widgetsDocVersion_PATH
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo widgetsDocVersion_PATH=/version/$(echo $GITHUB_REF | cut -d / -f 3 | cut -d v -f 2- | cut -d . -f 1,2)/ >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm install --legacy-peer-deps
          npm run build-storybook -- -o public

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'public'

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: storybook-static # The folder the action should deploy.
          TARGET_FOLDER: ${{ env.widgetsDocVersion_PATH }} # The folder the deployment folder content should be pushed to
          CLEAN: true # Automatically remove deleted files from the deploy branch
          CLEAN_EXCLUDE: '["version"]'