# This workflow will build the storybook documentation with GitHub Pages

name: Deploy documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm install
          npm run build-storybook -- -o public

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'public'
