# This workflow will build the storybook documentation with GitHub Pages

name: Build Storybook and publish to GH Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm install
          npm run build-storybook -- -o public

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'public'

  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Storybook
        run: echo "Create environment."
        environment:
          name: storybook/$CI_COMMIT_REF_SLUG
          url: https://github.com/nfdi4health/semlookp-widgets/$CI_COMMIT_REF_SLUG/storybook/
        only:
          - branches
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Pages
        cache:
          key: 'my-storybook'
          paths:
            - public
        run:
          - if [ "$CI_COMMIT_REF_NAME" = "main" ]; then
            mkdir -p public;
            touch public/index.html;
            echo "<!DOCTYPE HTML><script>window.location.href = 'https://github.com/nfdi4health/semlookp-widgets/main/storybook'</script>" > public/index.html;
            fi;
          - rm -rf "public/$CI_COMMIT_REF_SLUG"
          - mkdir -p "public/$CI_COMMIT_REF_SLUG";
          - mv storybook "public/$CI_COMMIT_REF_SLUG"
        artifacts:
          paths:
            - public